apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-products
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: app-products
  template:
    metadata:
      labels:
        app: app-products
    spec:
      containers:
      - name: app-products
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port | default 5002 }}
