apiVersion: v1
kind: Service
metadata:
  name: app-products
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5002 # Le port exposé par ton Flask dans le Dockerfile
    protocol: TCP
  selector:
    app: app-products