apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 5002 }}
      targetPort: {{ .Values.containerPort | default 5002 }}
      protocol: TCP
      {{- if and (eq (.Values.service.type | default "ClusterIP") "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "svc.fullname" . }}