apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-frontend-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # 🎯 FORCE Nginx à envoyer le trafic au ClusterIP (10.43.23.146) plutôt qu'à l'IP du Pod (10.42.0.56)
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-frontend-preprod-service
            port:
              number: 5000