apiVersion: v1
kind: Service
metadata:
  name: app-users
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5001
    protocol: TCP
  selector:
    app: app-users