apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  namespace: devops-pipeline

spec:
  replicas: 1

  selector:
    matchLabels:
      app: app-frontend

  template:
    metadata:
      labels:
        app: app-frontend

      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "frontend-role"
        vault.hashicorp.com/agent-inject-secret-keycloak: "secret/frontend"
        vault.hashicorp.com/agent-inject-template-keycloak: |
          {{- with secret "secret/frontend" -}}
          keycloak-client-secret: {{ .Data.keycloak-client-secret }}
          {{- end }}

    spec:
      serviceAccountName: frontend-sa
      
      containers:
        - name: app-frontend
          image: 192.168.74.128:8082/app-frontend:v21
          
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend
  namespace: devops-pipeline

spec:
  selector:
    app: app-frontend

  type: NodePort

  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000