apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-frontend-preprod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ishakguechoud/devops-pipeline.git'
    targetRevision: develop
    path: app-frontend/chart
    helm:
      valueFiles:
      - values-preprod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: preprod-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-gateway-preprod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ishakguechoud/devops-pipeline.git'
    targetRevision: develop
    path: app-gateway/chart
    helm:
      valueFiles:
      - values-preprod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: preprod-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-products-preprod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ishakguechoud/devops-pipeline.git'
    targetRevision: develop
    path: app-products/chart
    helm:
      valueFiles:
      - values-preprod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: preprod-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-users-preprod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ishakguechoud/devops-pipeline.git'
    targetRevision: develop
    path: app-users/chart
    helm:
      valueFiles:
      - values-preprod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: preprod-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-frontend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ishakguechoud/devops-pipeline.git'
    targetRevision: main
    path: app-frontend/chart
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-gateway-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ishakguechoud/devops-pipeline.git'
    targetRevision: main
    path: app-gateway/chart
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-products-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ishakguechoud/devops-pipeline.git'
    targetRevision: main
    path: app-products/chart
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-users-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ishakguechoud/devops-pipeline.git'
    targetRevision: main
    path: app-users/chart
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true