replicaCount: 1

labels:
  environment: prod

# 📁 On ajoute la bifurcation vers le dossier de prod sur Nexus
image:
  repository: "workflow-devops/prod/app-frontend"
  tag: "Application13-20260707-1412"
service:
  type: NodePort
  port: 5000
  nodePort: 31000

env:
  KEYCLOAK_BASE_URL: "http://172.28.77.160:8086"
  KEYCLOAK_REALM: "zak-local"

serviceAccount:
  name: "frontend-sa"

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "frontend-role"
  vault.hashicorp.com/agent-inject-secret-keycloak: "secret/data/frontend"
  vault.hashicorp.com/agent-inject-template-keycloak: |
    {{ with secret "secret/data/frontend" -}}
    keycloak-client-secret: {{ index .Data.data "keycloak-client-secret" }}
    {{- end }}

ingress:
  enabled: true
  host: app.prod.zak-local