replicaCount: 1

labels:
  environment: preprod

# 📁 On ajoute la bifurcation vers le dossier de préprod sur Nexus
image:
  repository: "workflow-devops/preprod/app-frontend"
  tag: "Application158-20260708-1235"

service:
  type: NodePort
  port: 5000
  nodePort: 30010

env:
  KEYCLOAK_BASE_URL: "http://172.28.77.160:8086"
  KEYCLOAK_REALM: "zak-local"
  KEYCLOAK_CLIENT_ID: "app-frontend"
  # 🎯 On cible le DNS K8s de la gateway de préprod
  GATEWAY_URL: "http://app-gateway-preprod-service.preprod-platform.svc.cluster.local:5003"

serviceAccount:
  name: "frontend-sa"

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "frontend-role"
  vault.hashicorp.com/agent-inject-secret-keycloak: "secret/data/frontend"
  vault.hashicorp.com/agent-inject-template-keycloak: |
    {{ with secret "secret/data/frontend" -}}
    keycloak-client-secret: {{ index .Data.data "keycloak-client-secret" }}
    {{- end }}

ingress:
  enabled: true
  host: app.preprod.zak-local