replicaCount: 2

service:
  nodePort: 31000

# Tu dois rajouter cette section pour l'injection de Vault en Prod :
podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "frontend-role"
  vault.hashicorp.com/agent-inject-secret-keycloak: "secret/frontend"
  vault.hashicorp.com/agent-inject-template-keycloak: |
    {{ with secret "secret/frontend" }}
    keycloak-client-secret: {{ index .Data.data "keycloak-client-secret" }}
    {{ end }}