# 🏷️ Ajout des labels requis par tes fonctions _helpers.tpl
labels:
  environment: "dev"

containerPort: 5000

image:
  registry: "192.168.74.128:8082"
  repository: "app-frontend"
  tag: "latest"
  pullPolicy: "IfNotPresent"

service:
  type: NodePort
  port: 5000
  nodePort: null

env:
# 💡 En local (dev), on peut cibler le DNS interne du namespace par défaut ou l'IP de dev
  USERS_SERVICE_URL: "http://app-users:5001"
  PRODUCTS_SERVICE_URL: "http://app-products:5002"
  KEYCLOAK_BASE_URL: "http://172.28.77.160:8086" # IP de ton WSL (Docker)
  KEYCLOAK_REALM: "zak-local"
  KEYCLOAK_CLIENT_ID: "app-frontend"
  FLASK_SECRET_KEY: "une_cle_secrete_super_secure"

vault:
  role: "frontend-role"
  secretPath: "secret/data/frontend"

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "frontend-role"
  vault.hashicorp.com/agent-inject-secret-keycloak: "secret/data/frontend"
  vault.hashicorp.com/agent-inject-template-keycloak: |
    {{- with secret "secret/data/frontend" -}}
    keycloak-client-secret: {{ index .Data.data "keycloak-client-secret" }}
    {{- end -}}

serviceAccount:
  name: "frontend-sa"

ingress:
  enabled: false
  host: "app.prod.zak-local"