replicaCount: 1

labels:
  environment: preprod

image:
  repository: "workflow-devops/preprod/app-products"
  tag: "Application137-20260708-1113"

service:
  type: NodePort
  port: 5002
  nodePort: 30012

env: {}

podAnnotations: {}