replicaCount: 1

labels:
  environment: preprod

image:
  repository: "workflow-devops/preprod/app-products"
  tag: "Application116-20260708-0823"

service:
  type: NodePort
  port: 5002
  nodePort: 30012

env: {}

podAnnotations: {}