replicaCount: 1

labels:
  environment: prod

image:
  repository: "workflow-devops/prod/app-products"
  tag: "Application47-20260708-1320"
service:
  type: NodePort
  port: 5002
  nodePort: 30002

env: {}

podAnnotations: {}