replicaCount: 1

labels:
  environment: preprod

image:
  repository: "workflow-devops/preprod/app-users"
  tag: "Application142-20260708-1139"
service:
  type: NodePort
  port: 5001
  nodePort: 30011

serviceAccount:
  name: "users-sa"

env: {}

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "users-role"
  vault.hashicorp.com/agent-inject-secret-db: "secret/data/preprod/db"
  vault.hashicorp.com/agent-inject-template-db: |
    {{ with secret "secret/data/preprod/db" -}}
    export DB_HOST={{ index .Data.data "db_host" }}
    export DB_NAME={{ index .Data.data "db_name" }}
    export DB_USER="workflow_app"
    export DB_PASSWORD={{ index .Data.data "db_password" }}
    export DB_PORT={{ index .Data.data "db_port" }}
    {{- end }}