replicaCount: 1

labels:
  environment: preprod

image:
  repository: "workflow-devops/preprod/app-users"
  tag: "Application88-20260706-1851"
service:
  type: NodePort
  port: 5001
  nodePort: 30011

env:
  DB_HOST: "192.168.74.129"
  DB_NAME: "workflow"
  DB_USER: "workflow_app"
  DB_PASSWORD: "Guizak-56"

podAnnotations: {}