replicaCount: 2

labels:
  environment: prod

image:
  repository: "workflow-devops/prod/app-users"
  tag: "Application18-20260707-1422"
service:
  type: NodePort
  port: 5001
  nodePort: 30001

env: {}

serviceAccount:
  name: "users-sa"

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "users-role"
  vault.hashicorp.com/agent-inject-secret-db: "secret/data/users"
  vault.hashicorp.com/agent-inject-template-db: |
    {{ with secret "secret/data/users" -}}
    DB_HOST={{ index .Data.data "db-host" }}
    DB_NAME={{ index .Data.data "db-name" }}
    DB_USER={{ index .Data.data "db-user" }}
    DB_PASSWORD={{ index .Data.data "db-password" }}
    {{- end }}